### ISSUE TITLE
Open and Read a File - nothing displaying on my browser.

### ISSUE THREAD

**Issue by bhavish030** [adprofy/Php-Hadoop-Hdfs#1]
Hello,
I am trying to connect to my hdfs to open and read a file. My php version is 5.6. The problem is when i load my page on my apache web server nothing happens.
This is my php script (webhdfs.php):
```
<?php

    $host = "localhost";
    $port = 9870;

    $hdfsDir = "/testing2/file.txt";

    $hdfs = new \Hdfs\Web();

    $hdfs->configure($host, $port);      

    $hdfs->readDir ($hdfsDir) ;
    
    echo $hdfs;
?>
```
I've tried to run it on the command line and this is the output:
```
hadoop@hadoop-HP-Pro3500-Series:/var/www/html$ php webhdfs.php 
test <br>test1 <br>PHP Fatal error:  Class 'Hdfs\Web' not found in /var/www/html/webhdfs.php on line 8
```
It seems that the class does not exist on my php.
Any solution for this please.
Thank you.

**Comment by RealyUniqueName** [comment]
You need an autoloader to load required classes: http://php.net/manual/en/function.spl-autoload-register.php
